---
    - name: GROUPS
      debug:
        msg: "RUN DMC: Hard times spreading just like the flu/Watch out homeboy, don't let it catch you"

    - include_tasks: ../../../roles/splunk_monitor/tasks/initialize_standalone_search_head.yml

    - name: sleep
      wait_for:
        timeout: 45

    - name: Flush restart handlers
      meta: flush_handlers

    - name: Fetch distributed peers
      uri:
        url: "{{ cert_prefix }}://127.0.0.1:{{ splunk.svc_port }}/services/search/distributed/peers?output_mode=json"
        method: GET
        user: "{{ splunk.admin_user }}"
        password: "{{ splunk.password }}"
        validate_certs: false
        status_code: 200
        timeout: 10
        return_content: yes
      register: distributed_info
      no_log: "{{ hide_password }}"

    - name: Distributed Info
      debug:
        var: distributed_info

    - name: Create search strings
      set_fact:
        index_string: "{{ distributed_info['json']['entry'] | selectattr('content.server_roles','defined') | selectattr('content.server_roles', 'search', 'indexer') | map(attribute='name') | list | join('&member=') }}"
        search_head_string: "{{ distributed_info['json']['entry'] | selectattr('content.server_roles','defined') | selectattr('content.server_roles', 'search', 'search_head') | map(attribute='name') | list | join('&member=') }}"
        cluster_master_string: "{{ distributed_info['json']['entry'] | selectattr('content.server_roles','defined') | selectattr('content.server_roles', 'search', 'cluster_master') | map(attribute='name') | list | join('&member=') }}"
        deployment_server_string: "{{ distributed_info['json']['entry'] | selectattr('content.server_roles','defined') | selectattr('content.server_roles', 'search', 'deployment_server') | map(attribute='name') | list | join('&member=') }}"
        license_master_string: "{{ distributed_info['json']['entry'] | selectattr('content.server_roles','defined') | selectattr('content.server_roles', 'search', 'license_master') | map(attribute='name') | list | join('&member=') }}"
        configured_peers: "{% if splunk.role == 'splunk_search_head' and splunk.role == 'splunk_cluster_master' %}distributed_info['json']['entry'] | map(attribute='name') | list | join(','){% else %}{% endif %}"

    - include_tasks: ../../../roles/splunk_monitor/tasks/post_calls.yml

    - include_tasks: ../../../roles/splunk_monitor/tasks/initialize_dmc.yml